apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::004490858278:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-Dr3JKjVJiZyC
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::004490858278:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-16T01:01:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1235"
  uid: 0b53d0b1-cb72-4942-b2b4-f9d8ed1d2739
